# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
project_name: lr
builds:
  - <<: &build_defaults
      binary: lr
      main: ./app/lr
      ldflags:
        - -s -w -X github.com/loginradius/lr-cli/internal/build.Version={{.Version}} -X github.com/loginradius/lr-cli/internal/build.Date={{time "2006-01-02"}}
        - -X main.updaterEnabled=cli/cli
    id: macos
    goos: [darwin]
    goarch: [amd64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]
    env:
      - CGO_ENABLED=0

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64]

archives:
  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    replacements:
      darwin: macOS
    format: tar.gz
    files:
      - LICENSE
  - id: windows
    builds: [windows]
    <<: *archive_defaults
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
brews:
  - folder: Formula
    homepage: https://github.com/loginradius/lr-cli
    description: "LoginRadius CLI to support LoginRadius API's and workflow!"
    tap:
      owner: loginradius
      name: homebrew-tap
    test:
      system "lr --help"
